global:
  scrape_interval: "5s"
  evaluation_interval: "5s"


scrape_configs:
  - job_name: 'fastapi-app'
    metrics_path: /metrics
    static_configs:
    - targets: ['localhost:8000']  # Replace with your Python app's IP and port

